server:
  port: 8040
spring:
  profiles:
    active: dev
  application:
    name: gateway
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      enabled: true
      eager: true
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: content-center
          uri: lb://content-center
          predicates:
            - Path=/**
        - id: aliyun_route
          uri: https://www.aliyun.com/
          predicates:
            - Path=/product/**
        - id: httpbin_route
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - RewritePath=/httpbin/(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

