server:
  port: 8040
spring:
  profiles:
    active: dev
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: content-center
          uri: lb://content-center
          predicates:
            - Path=/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

